name: automl-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - kedro==0.18.11
    - scikit-learn==1.1.3
    - pandas==2.0.3
    - plotly==5.15.0
    - ipywidgets==7.6
    - streamlit==1.24.0
    - scikit-optimize==0.8.1
    - matplotlib==3.7.2
    - seaborn==0.12
    - jupyterlab==3.5.3
    - xgboost==1.7.6
